export default {
  editor: {
    "card.label_import": "Import",
    "card.label_export": "Export",
    "editor.main_title": "Haupt Entitäten",
    "editor.solar_section": "Solar/PV",
    "editor.grid_section": "Netz Import/Export",
    "editor.battery_section": "Batterie",
    "editor.consumers_section": "Zusätzliche Verbraucher",
    "editor.options_section": "Darstellung & Optionen",
    "editor.group_layout": "Layout & Ansicht",
    "editor.group_appearance": "Effekte & Darstellung",
    "editor.group_pipes": "Röhren & Verbraucher",
    "editor.group_compact": "Kompakte Ansicht (evcc)",
    "editor.compact_view_enable": "Kompakte Ansicht aktivieren",
    "editor.compact_glow": "Neon Glow in kompakter Ansicht",
    "editor.compact_icons_in_bracket": "Icons in die Klammern setzen",
    "editor.compact_icons_in_bracket_hint": "Aus: Die Icons stehen innerhalb der Klammern, die Klammerlinie läuft durchgehend. An: Die Icons sitzen mittig auf der Klammerlinie und unterbrechen sie.",
    "editor.compact_bar_selfuse": "Einspeisung in den Balken aufnehmen",
    "editor.compact_bar_selfuse_hint": "Aus: Der mittlere Balken zeigt nur die Quellen (Solar, Batterie, Netz) in voller Höhe, die Einspeisung erscheint allein als Klammer darunter. An: Die Einspeisung wandert als eigenes farbiges Segment in den mittleren Balken — Solar und Batterie zeigen dann nur noch den Anteil, der wirklich im Haus verbraucht wird. Die Klammern oben zeigen unverändert die vollen Quellen.",
    "editor.battery_charge_color": "🔋 Ladung",
    "editor.battery_discharge_color": "⚡ Entladung",
    "editor.battery_split_color_hint": "In der kompakten Ansicht lassen sich Ladung und Entladung getrennt einfärben. Bubble = Balkensegment, Pipe = Klammerlinie, Text = Wert, Icon = Symbol, Secondary = Beschriftung in der Detailliste.",
    "editor.flow_rate_title": "Flussraten (W) an Röhren anzeigen",
    "editor.invert_battery": "Wert umkehren (+/-)",
    "editor.invert_battery_hint": "Für Sensoren mit umgekehrtem Vorzeichen (Laden negativ / Entladen positiv, z. B. GivTCP, Solax). Standard: Laden positiv, Entladen negativ. Bei falscher Lade-/Flussrichtung (z. B. Solar/Netz→Batterie-Röhre beim Entladen oder fehlende Batterie→Haus-Röhre) hier umkehren.",
    "editor.label_toggle": "Label statt secondary entity anzeigen",
    "editor.horizontal_view": "Horizontale Ansicht",
    "editor.diamond_view": "Diamant Ansicht",
    "editor.use_boxes": "Boxen mit runden Ecken statt Kreise",
    "editor.compact_details": "Details für Kompakte Ansicht",
    "editor.hide_inactive": "Inaktive Röhren ausblenden",
    "editor.entity": "Kombinierter Batterie Sensor (W)",
    "editor.label": "Beschriftung",
    "editor.icon": "Icon",
    "editor.back": "Zurück",
    "editor.battery_soc_label": "Ladestand (%)",
    "editor.house_total_title": "🏠 Gesamtverbrauch (optional)",
    "editor.house_sensor_label": "Sensor für Hausverbrauch (optional)",
    "editor.house_sensor_hint": "Wird benötigt, damit das Haus-Icon anklickbar ist (more-details). Ansonsten wird der Hausverbrauch berechnet.",
    "editor.consumer_1_title": "🚗 Links (Lila)",
    "editor.consumer_2_title": "♨️ Mitte (Orange)",
    "editor.consumer_3_title": "🏊 Rechts (Türkis)",
    "editor.zoom_label": "🔍 Zoom (Standard View)",
    "editor.neon_glow": "Neon Glow",
    "editor.donut_chart": "Donut Chart (Grid/Haus)",
    "editor.comet_tail": "Comet Tail Effect",
    "editor.dashed_line": "Dashed Line Effect",
    "editor.tinted_background": "Farbiger Hintergrund in Kreisen",
    "editor.colored_values": "Farbige Textwerte",
    "editor.hide_consumer_icons": "Icons unten ausblenden",
    "editor.force_watt_display": "Alle Werte in Watt anzeigen",
    "editor.force_kw_display": "Alle Werte in kW anzeigen",
    "editor.force_unit_display_hint": "Standardmäßig werden Werte bis 1000 W in Watt und darüber in kW angezeigt. Mit diesen Schaltern kann stattdessen durchgängig eine Einheit erzwungen werden. Ist keiner der beiden aktiv, gilt die Standard-Darstellung.",
    "editor.solar_sensor_label": "Solar-Sensor (W)",
    "editor.solar_extra_label": "Weiterer Solar-Sensor (W)",
    "editor.add_solar_sensor": "Weitere Solaranlage hinzufügen",
    "editor.solar_extra_hint": "Für Anlagen mit mehreren Solar-Wechselrichtern: Über \"Weitere Solaranlage hinzufügen\" lassen sich beliebig viele zusätzliche Solar-Sensoren hinterlegen. Alle Sensoren werden addiert und als ein gemeinsamer Solarwert dargestellt.",
    "editor.invert_consumer": "Sensorwert invertieren (+/-)",
    "editor.invert_grid": "Wert umkehren (+/-)",
    "editor.secondary_sensor": "Zweiter Sensor (nur Anzeige)",
    "editor.tertiary_sensor": "Dritter Sensor (nur Anzeige)",
    "editor.tertiary_sensor_hint": "Zweiter und dritter Sensor werden in einer Zeile mit \" / \" getrennt angezeigt und nutzen beide die Secondary-Farbe.",
    "editor.grid_to_battery_sensor": "Netz-zu-Batterie Sensor (W, Optional)",
    "editor.grid_to_battery_hint": "Optional: separater Sensor für den Netz-zu-Batterie Fluss. Wenn leer, wird der Wert automatisch berechnet.",
    "editor.grid_combined_sensor": "Kombinierter Netz-Sensor (W, Optional)",
    "editor.grid_combined_hint": "Ein Sensor für Import UND Export: positiv = Import, negativ = Export. Überschreibt den kombinierten Import/Export Sensor.",
    "editor.color_picker": "Bubble",
    "editor.pipe_color": "Pipe",
    "editor.export_color": "↑ Einspeisung / Export",
    "editor.export_color_hint": "Bubble färbt den Netz-Kreis beim Einspeisen, Pipe die Export-Röhre, Text den Wert, Icon das Symbol und Secondary die Beschriftung in der Detailliste der kompakten Ansicht. Alle folgen der Bubble-Farbe, solange sie nicht eigens gesetzt sind. Hinweis: Bubble wirkt in der kompakten Ansicht nur, wenn „Einspeisung in den Balken aufnehmen\" aktiv ist.",
    "editor.export_icon": "Icon für Export",
    "editor.export_icon_hint": "Überschreibt das Standard-Icon (mdi:arrow-right-box) für die Export-Klammer und das Detail-Icon in der kompakten Ansicht.",
    "editor.consumer_unit_kw": "Sensor meldet in kW",
    "editor.show_consumer_always": "Verbraucher bei null Watt anzeigen",
    "editor.show_producer_always": "Erzeuger bei null Watt anzeigen",
    "editor.battery_hide_soc_threshold": "Batterie ausblenden unter Ladestand (%)",
    "editor.battery_hide_soc_threshold_hint": "Die Batterie wird ausgeblendet, sobald der Ladestand auf oder unter diesen Wert fällt.",
    "editor.battery_charge_sensor": "Batterie-Ladung Sensor (W, Optional)",
    "editor.battery_discharge_sensor": "Batterie-Entladung Sensor (W, Optional)",
    "editor.battery_separate_hint": "Optional: Separate Sensoren für Laden/Entladen. Überschreiben den Hauptsensor für die Berechnung.",
    "editor.battery_multi_title": "Mehrere Batterien",
    "editor.battery_multi_hint": "Für Anlagen mit mehreren Batteriespeichern: Über „Weitere Batterie hinzufügen\" lassen sich bis zu 3 zusätzliche Batterien (insgesamt 4) hinterlegen. Pro Batterie ist wie beim Hauptspeicher ein gemeinsamer Sensor (positiv = laden, negativ = entladen) oder je ein getrennter Lade- und Entlade-Sensor möglich. An der Röhre wird stets die Summe aller Batterien angezeigt. Wie die Batterien im Kreis dargestellt werden, legst du mit den beiden Schaltern weiter unten fest.",
    "editor.battery_extra_title": "Batterie",
    "editor.add_battery": "Weitere Batterie hinzufügen",
    "editor.battery_max_hint": "Es werden maximal 4 Batterien unterstützt.",
    "editor.battery_split_ring": "Aufteilung: Ring-Segmente (SOC je Batterie)",
    "editor.battery_split_quarters": "Aufteilung: Kuchensegmente (max 4)",
    "editor.battery_split_hint": "Zwei Darstellungen für mehrere Batterien (ab 2 Batterien wirksam, schließen sich gegenseitig aus): „Ring-Segmente\" teilt den Kreis in gleich große Bögen — jeder Bogen füllt sich nach dem SOC einer Batterie; Batterie-Icon und Ø-SOC bleiben mittig. „Kuchensegmente\" teilt den Kreis in bis zu vier Sektoren mit der SOC-Zahl je Batterie (≤ 20 % rot) und zeigt in der Mitte den durchschnittlichen SOC.",
    "editor.consumer_hide_pipe": "Pipe bei geringer Leistung ausblenden",
    "editor.consumer_pipe_threshold": "Pipe-Schwellenwert (Watt)",
    "editor.consumer_not_set": "nicht gesetzt",
    "editor.consumer_standby": "Standby-Werte ausblenden",
    "editor.consumer_standby_threshold": "Standby-Schwellenwert (Watt)",
    "editor.consumer_standby_hint": "Werte unterhalb des Schwellenwerts werden als 0 W gewertet, der Verbraucher wird dadurch ausgeblendet.",
    "editor.text_color": "Text",
    "editor.icon_color": "Icon",
    "editor.secondary_color": "Secondary",
    "editor.battery_charge_via_house": "Batterie-Ladung über Hausverbrauch umleiten",
    "editor.battery_show_power": "Zeige Leistung statt SoC",
    "editor.solar_unit_kw": "Solar in kW anzeigen",
    "editor.grid_threshold": "Netz-Schwellenwert (W)",
    "editor.grid_threshold_hint": "Netzleistung unterhalb dieses Wertes zählt als 0 W. Verhindert, dass die Anzeige bei einem ausgeglichenen Netz ständig zwischen Bezug und Einspeisung wechselt. 0 = aus.",
    "editor.grid_unit_kw": "Grid in kW anzeigen",
    "editor.battery_unit_kw": "Batterie Leistung in kW anzeigen",
    "editor.consumer_4_title": "⚡ Reihe 2 Links (Gelb)",
    "editor.consumer_5_title": "💡 Reihe 2 Rechts (Indigo)",
  },
  card: {
    "card.label_solar": "Solar",
    "card.label_grid": "Netz",
    "card.label_battery": "Batterie",
    "card.label_house": "Verbrauch",
    "card.label_car": "E-Auto",
    "card.label_heater": "Heizung",
    "card.label_pool": "Pool",
    "card.label_consumer_4": "Verbr. 4",
    "card.label_consumer_5": "Verbr. 5",
    "card.label_export": "Einspeisung",
    "card.label_in": "Erzeugung",
    "card.label_out": "Verbrauch",
  }
};
