export default {
  editor: {
    "card.label_import": "Import",
    "card.label_export": "Export",
    "editor.main_title": "Main Entities",
    "editor.solar_section": "Solar",
    "editor.grid_section": "Grid Connection",
    "editor.battery_section": "Battery",
    "editor.consumers_section": "Additional Consumers",
    "editor.options_section": "Appearance & Options",
    "editor.group_layout": "Layout & View",
    "editor.group_appearance": "Effects & Appearance",
    "editor.group_pipes": "Pipes & Consumers",
    "editor.group_compact": "Compact View (evcc)",
    "editor.compact_view_enable": "Enable Compact View",
    "editor.compact_glow": "Neon Glow in Compact View",
    "editor.compact_icons_in_bracket": "Place icons on the bracket line",
    "editor.compact_icons_in_bracket_hint": "Off: the icons sit inside the brackets and the bracket line stays unbroken. On: the icons are centered on the bracket line and interrupt it.",
    "editor.compact_bar_selfuse": "Include export in the bar",
    "editor.compact_bar_selfuse_hint": "Off: the middle bar shows the sources only (solar, battery, grid) at full size, and the export appears as a bracket below it. On: the export moves into the middle bar as its own colored segment — solar and battery then only show the share actually used in the house. The top brackets keep showing the full sources.",
    "editor.battery_charge_color": "🔋 Charge",
    "editor.battery_discharge_color": "⚡ Discharge",
    "editor.battery_split_color_hint": "In the compact view charge and discharge can be colored separately. Bubble = bar segment, Pipe = bracket line, Text = value, Icon = symbol, Secondary = label in the details list.",
    "editor.flow_rate_title": "Show Flow Rates (W) on pipes",
    "editor.invert_battery": "Invert Power Value (+/-)",
    "editor.invert_battery_hint": "For sensors with the opposite sign (charging negative / discharging positive, e.g. GivTCP, Solax). Default: charging positive, discharging negative. Flip this if the charge/flow direction is wrong (e.g. a Solar/Grid→Battery pipe while discharging, or a missing Battery→House pipe).",
    "editor.label_toggle": "Show label instead of secondary entity",
    "editor.horizontal_view": "Horizontal View",
    "editor.diamond_view": "Diamond View",
    "editor.use_boxes": "Rounded boxes instead of circles",
    "editor.compact_details": "Compact View Details",
    "editor.hide_inactive": "Hide Inactive Pipes",
    "editor.entity": "Combined Battery Sensor (W)",
    "editor.label": "Label",
    "editor.icon": "Icon",
    "editor.back": "Back",
    "editor.battery_soc_label": "State of Charge (%)",
    "editor.house_total_title": "🏠 Total Consumption (optional)",
    "editor.house_sensor_label": "Sensor for House Consumption (optional)",
    "editor.house_sensor_hint": "Required to make the house icon clickable (more-details). Otherwise, the house consumption is calculated.",
    "editor.consumer_1_title": "🚗 Left (Purple)",
    "editor.consumer_2_title": "♨️ Center (Orange)",
    "editor.consumer_3_title": "🏊 Right (Cyan)",
    "editor.zoom_label": "🔍 Zoom (Standard View)",
    "editor.neon_glow": "Neon Glow",
    "editor.donut_chart": "Donut Chart (Grid/House)",
    "editor.comet_tail": "Comet Tail Effect",
    "editor.dashed_line": "Dashed Line Effect",
    "editor.tinted_background": "Tinted Background in Bubbles",
    "editor.colored_values": "Colored Text Values",
    "editor.hide_consumer_icons": "Hide Consumer Icons",
    "editor.force_watt_display": "Always show values in Watt",
    "editor.force_kw_display": "Always show values in kW",
    "editor.force_unit_display_hint": "By default values up to 1000 W are shown in Watt and above in kW. These switches let you force a single unit throughout instead. If neither is enabled, the default behavior applies.",
    "editor.solar_sensor_label": "Solar Sensor (W)",
    "editor.solar_extra_label": "Additional Solar Sensor (W)",
    "editor.add_solar_sensor": "Add another solar system",
    "editor.solar_extra_hint": "For setups with multiple solar inverters: use \"Add another solar system\" to configure as many additional solar sensors as needed. All sensors are summed and shown as a single combined solar value.",
    "editor.invert_consumer": "Invert Sensor Value (+/-)",
    "editor.invert_grid": "Invert Power Value (+/-)",
    "editor.secondary_sensor": "Secondary Sensor (display only)",
    "editor.tertiary_sensor": "Third Sensor (display only)",
    "editor.tertiary_sensor_hint": "The second and third sensor share one line, separated by \" / \", and both use the secondary color.",
    "editor.grid_to_battery_sensor": "Grid to Battery Sensor (W, optional)",
    "editor.grid_to_battery_hint": "Optional: separate sensor for grid-to-battery flow. If empty, the value is calculated automatically.",
    "editor.grid_combined_sensor": "Combined Grid Sensor (W, Optional)",
    "editor.grid_combined_hint": "Single sensor for import AND export: positive = import, negative = export. Overrides combined import/export sensor.",
    "editor.color_picker": "Bubble Color",
    "editor.pipe_color": "Pipe Color",
    "editor.export_color": "↑ Export",
    "editor.export_color_hint": "Bubble colors the grid node while exporting, Pipe the export pipe, Text the value, Icon the symbol and Secondary the label in the compact view details list. All follow the bubble color until set explicitly. Note: Bubble only shows in the compact view when \"Include export in the bar\" is enabled.",
    "editor.export_icon": "Export icon",
    "editor.export_icon_hint": "Overrides the default icon (mdi:arrow-right-box) used for the export bracket and the compact-view detail icon.",
    "editor.consumer_unit_kw": "Sensor reports in kW",
    "editor.show_consumer_always": "Show Consumers at zero watts",
    "editor.show_producer_always": "Show Producers at zero watts",
    "editor.battery_hide_soc_threshold": "Hide battery below charge level (%)",
    "editor.battery_hide_soc_threshold_hint": "The battery is hidden once its charge level drops to or below this value.",
    "editor.battery_charge_sensor": "Battery Charge Sensor (W, Optional)",
    "editor.battery_discharge_sensor": "Battery Discharge Sensor (W, Optional)",
    "editor.battery_separate_hint": "Optional: Separate sensors for charge/discharge. Override the main sensor for calculations.",
    "editor.battery_multi_title": "Multiple Batteries",
    "editor.battery_multi_hint": "For setups with multiple battery storages: use \"Add another battery\" to configure up to 3 additional batteries (4 in total). Each battery supports either a single combined sensor (positive = charging, negative = discharging) or separate charge and discharge sensors, just like the primary battery. The pipe always shows the sum of all batteries. How the batteries are drawn inside the circle is set with the two switches below.",
    "editor.battery_extra_title": "Battery",
    "editor.add_battery": "Add another battery",
    "editor.battery_max_hint": "A maximum of 4 batteries is supported.",
    "editor.battery_split_ring": "Split: ring segments (SoC per battery)",
    "editor.battery_split_quarters": "Split: pie segments (max 4)",
    "editor.battery_split_hint": "Two display styles for multiple batteries (active from 2 batteries, mutually exclusive): \"Ring segments\" divides the circle into equal arcs — each arc fills according to one battery's SoC, while the battery icon and the average SoC stay in the center. \"Pie segments\" splits the circle into up to four sectors showing each battery's SoC value (red \u2264 20%), with the average SoC in the center.",
    "editor.consumer_hide_pipe": "Hide pipe at low power",
    "editor.consumer_pipe_threshold": "Pipe Threshold (Watts)",
    "editor.consumer_not_set": "not set",
    "editor.consumer_standby": "Hide standby values",
    "editor.consumer_standby_threshold": "Standby Threshold (Watts)",
    "editor.consumer_standby_hint": "Readings below the threshold count as 0 W, which hides the consumer entirely.",
    "editor.text_color": "Text Color",
    "editor.icon_color": "Icon Color",
    "editor.secondary_color": "Secondary",
    "editor.battery_charge_via_house": "Battery charge via house consumption",
    "editor.battery_show_power": "Show power instead of SoC",
    "editor.solar_unit_kw": "Show Solar in kW",
    "editor.grid_threshold": "Grid threshold (W)",
    "editor.grid_threshold_hint": "Grid power below this value counts as 0 W. Prevents the display from flipping between import and export while the grid is balanced. 0 = off.",
    "editor.grid_unit_kw": "Show Grid in kW",
    "editor.battery_unit_kw": "Show battery power in kW",
    "editor.consumer_4_title": "⚡ Row 2 Left (Yellow)",
    "editor.consumer_5_title": "💡 Row 2 Right (Indigo)",
  },
  card: {
    "card.label_solar": "Solar",
    "card.label_grid": "Grid",
    "card.label_battery": "Battery",
    "card.label_house": "Consumption",
    "card.label_car": "Car",
    "card.label_heater": "Heater",
    "card.label_pool": "Pool",
    "card.label_consumer_4": "Cons. 4",
    "card.label_consumer_5": "Cons. 5",
    "card.label_export": "Export",
    "card.label_in": "In",
    "card.label_out": "Out",
  }
};
