export default {
  editor: {
    "card.label_import": "Import",
    "card.label_export": "Export",
    "editor.main_title": "Main Entities",
    "editor.solar_section": "Solar",
    "editor.grid_section": "Grid Connection",
    "editor.battery_section": "Battery",
    "editor.consumers_section": "Additional Consumers",
    "editor.options_section": "Appearance & Options",
    "editor.flow_rate_title": "Show Flow Rates (W) on pipes",
    "editor.invert_battery": "Invert Power Value (+/-)",
    "editor.label_toggle": "Show Label in Bubble",
    "editor.compact_view": "Compact View (evcc)",
    "editor.hide_inactive": "Hide Inactive Pipes",
    "editor.entity": "Entity (Watt)",
    "editor.label": "Label",
    "editor.icon": "Icon",
    "editor.back": "Back",
    "editor.battery_soc_label": "State of Charge (%)",
    "editor.house_total_title": "🏠 Total Consumption (optional)",
    "editor.house_sensor_label": "Sensor for House Consumption (optional)",
    "editor.house_sensor_hint": "Required to make the house icon clickable (compact view).",
    "editor.consumer_1_title": "🚗 Left (Purple)",
    "editor.consumer_2_title": "♨️ Center (Orange)",
    "editor.consumer_3_title": "🏊 Right (Cyan)",
    "editor.zoom_label": "🔍 Zoom (Standard View)",
    "editor.neon_glow": "Neon Glow",
    "editor.donut_chart": "Donut Chart (Grid/House)",
    "editor.comet_tail": "Comet Tail Effect",
    "editor.dashed_line": "Dashed Line Effect",
    "editor.tinted_background": "Tinted Background in Bubbles",
    "editor.colored_values": "Colored Text Values",
    "editor.hide_consumer_icons": "Hide Consumer Icons",
    "editor.invert_consumer_1": "Invert Sensor Value (+/-)",
    "editor.secondary_sensor": "Secondary Sensor (display only)",
    "editor.grid_to_battery_sensor": "Grid to Battery Sensor (Watt)",
    "editor.grid_to_battery_hint": "Optional: separate sensor for grid-to-battery flow. If empty, the value is calculated automatically.",
    "editor.grid_combined_sensor": "Combined Grid Sensor (W, Optional)",
    "editor.grid_combined_hint": "Single sensor for import AND export: positive = import, negative = export. Overrides separate import/export sensors.",
    "editor.color_picker": "Custom Color",
  },
  card: {
    "card.label_solar": "Solar",
    "card.label_grid": "Grid",
    "card.label_battery": "Battery",
    "card.label_house": "Consumption",
    "card.label_car": "Car",
    "card.label_import": "Import",
    "card.label_export": "Export",
  }
};
